### ISSUE TITLE
fortran bindings for OSX?

### ISSUE THREAD

**Issue by ltalirz** [conda-forge/libxc-feedstock#15]
I notice that the fortran bindings are currently explicitly disabled for OSX in
https://github.com/conda-forge/libxc-feedstock/blob/258cfdc26eb19b4605e92d03de340224823e95f8/recipe/build.sh#L3
This currently prevents me from creating a libxc-enabled cp2k conda-package for OSX.

I guess there is a reason for this - what happens to be the problem?

**Comment by loriab** [comment]
Hi, I added the osx and windows libxc builds in https://github.com/conda-forge/libxc-feedstock/pull/8 . The reasons for those being C-only were:
* I only have psi4 (uses C libs) downstream, so I didn't want to put out a Fortran lib that hadn't been tested
* I wasn't sure about the best packages pattern for all-libs-together vs. libxc-fortran depending on libxc-base
  * conda-forge fortran has more constraints and different pinning than defaults fortran, making a fortran-including pkg less versatile than c-only on mac
  * on linux, c-f fortran brings gomp, iirc, which I'm not sure why libxc itself needs. this can interfere with omp/iomp5-linked libs

So, it's disabled because of reservations, and I didn't need it. No reason to not try further, since you do need it.

**Comment by ltalirz** [comment]
Thanks for the quick reply!
I was not aware of the compatibility issues that may arise. Should we try making the fortran-enabled build a [variant](https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html) both on Linux and MacOS?

**Comment by jan-janssen** [comment]
We can create multiple outputs with a single recipe - here is an example https://github.com/conda-forge/fenics-feedstock/blob/master/recipe/meta.yaml - in case that helps.

**Comment by ltalirz** [comment]
Coming back to this: it looks to me like there are (at least) two options:

 1. Always include the fortran interface (and potentially reduce compatibility)
 2. add a variable to the `conda_build_config.yaml` whose value determines whether the fortran interface. make dependencies dependent on the value of that variable. Users can install the variant with `conda install -c conda-forge libxc=*=*variant*`
 3. add a separate output to the package, e.g. `libxc-fortran`

To me the third option suggested by @jan-janssen looks like a good fit.
@loriab do you want me to prepare a PR?

**Comment by loriab** [comment]
The third option of separate output is much preferred over the second option of adding a variant to my understanding. Variants are designed for mutually incompatible choices like py36/py37, mpich/nompi, mkl/openblas. The thing to watch on separate outputs is that the dependencies get assigned rightly to each package output. Requirements packages listed in the recipe outer are those present for the build. Requirements packages for the inner outputs are those used to compute the dependencies of each built package.

Dredging up a few more details from https://gitlab.com/libxc/libxc/-/merge_requests/435, I think the missing part to separation is handling target availability logic in libxc-config.cmake. For the C libxc pkg on c-f, the buildsys thinks both C & Fortran are available targets, so both the cmake components are available. But if the Fortran libxc pkg from c-f is installed, that same libxc-config.cmake file now correctly should be the original one that makes both C & F available. I don't know how involved you are in cmake as to whether that makes sense. And maybe cmake detection is a lesser consideration for a c-f package.

Sure, PR welcome!

**Comment by ltalirz** [comment]
@loriab Coming back to this since the issue popped up again with another code.

My first question is about timing: do you suggest to remove the fortran bindings from the linux package for `libxc` (breaking backwards-compatibility) when creating the `libxc-fortran` output?
Or is there a time (e.g. next major libxc release) that would be better to break backwards compatibility?

Depending on this, it might be more straightforward to just add the fortran bindings to the osx package as well and then remove them from both once the time has come.

As for the multi-output option, you mention
> libxc-fortran depending on libxc-base

I'm still not that much of a conda-forge expert (less than you probably), so I would need some advice here.

I was originally thinking of the standard `libxc` package that does not include the wrappers, and `libxc-fortran` that would include everything (directly within the package, not via a dependency on `libxc`).

It seems to me that depending explicitly on `libxc` in the `libxc-fortran` output might lead to issues  - e.g. if there is a new major release, can one then depend on the unreleased `libxc` from the same `meta.yaml`?

**Comment by loriab** [comment]
> Dredging up a few more details from https://gitlab.com/libxc/libxc/-/merge_requests/435, I think the missing part to separation is handling target availability logic in libxc-config.cmake. For the C libxc pkg on c-f, the buildsys thinks both C & Fortran are available targets, so both the cmake components are available. But if the Fortran libxc pkg from c-f is installed, that same libxc-config.cmake file now correctly should be the original one that makes both C & F available. I don't know how involved you are in cmake as to whether that makes sense. And maybe cmake detection is a lesser consideration for a c-f package.

fwiw, I think I've addressed this obstacle in https://gitlab.com/libxc/libxc/-/merge_requests/543 . A base or "c" libxc pkg can install the C library, LibxcConfig.cmake, and LibxcTargets-C-*.cmake, and a libxc-fortran pkg can install libxcf03.so and LibxcTargets-Fortran-*.cmake without clobbering or computing the wrong components availability.

**Comment by ltalirz** [comment]
Cheers! This still leaves the questions from above, would you care to comment?

> do you suggest to remove the fortran bindings from the linux package for `libxc` (breaking backwards-compatibility)

> Should there be a `libxc-fortran` that _depends_ on `libxc` or is it fine to create a `libxc-fortran` that includes both the C and the fortran interface?

**Comment by loriab** [comment]
> Should there be a libxc-fortran that depends on libxc or is it fine to create a libxc-fortran that simply includes both the C and the fortran interface?

Provided we can get multiple outputs from the single recipe with the right deps for each (namely, no fortran lib dependence for the c-lib package), I think it's cleaner and more customary in conda to have non-overlapping packages. I've seen a c-lib and a python extension have separate copies of the same library, but those are in different locations. The provision should be simple, but I've met one difficult case that I couldn't get to work how I wanted.

> do you suggest to remove the fortran bindings from the linux package for libxc (breaking backwards-compatibility)

That would be my inclination (though the fallout wouldn't hit me personally). We can grep the feedstock aggregate and find and notify libxc dependees to have them update recipes. Or maybe ping the repo maintainers in this thread (after getting over the previous obstacle) to see if a package split for linux would cause trouble. https://github.com/search?q=org%3Aconda-forge+libxc&type=code
