### ISSUE TITLE
cmake for linux/mac

### ISSUE THREAD

**Issue by loriab** [conda-forge/libxc-feedstock#2]
Hi, @bjodah, would you care to collaborate on this recipe?

I'm the one who wrote the https://github.com/psi4/psi4meta/tree/master/conda-recipes/libxc . Only reason I've kept that and others on a separate channel is because of the special performance optimization flags for Intel compilers. Thanks for starting this recipe up here at `c-f`.

My reservation is that this recipe uses libtool for the build on Linux & Mac rather than cmake. The cmake build writes out the `.pc` files that libtool detection needs, as well as its own `LibxcConfig.cmake` for cmake detection. But the libtool build can only write out its own files. The package for which I packaged up libxc, psi4, needs the cmake Config files, so if someone accidentally tried to build psi against this c-f conda package, they would get an error. The Libxc people know about my conda package, so I doubt they'd be against this one using cmake (unless you've heard to the contrary).

I was also thinking that the `run_exports` could be generalized from `x.x` to `x`, since I know from experience how committed they are to preserving semantic versioning contracts.

**Comment by bjodah** [comment]
Hi @loriab, I used your recipe as a starting point, but I was unsure if your cmake config would cause any problems when using `libxc` with other packages. But I also saw that they even use your cmake scripts to run CI on AppVeyor under windows.

I am all for changing this recipe to use CMake throughout, I saw that the bot picked up a new version of libxc, do you want to make a change to the recipe before we merge that one perhaps?

And no, I haven't been in contact with the developers at all, I'm  just hoping to add a few ab initio programs to `c-f`. Hopefully `gpaw`, and perhaps others as well (I've seen recipes for [abinit](https://github.com/abinit/abiconda)).

**Comment by loriab** [comment]
With the `.pc` files and now the Fortran interfaces building through cmake, I think it's inclusive enough to be used by both libtool- and cmake-detecting downstreams. But I don't know this in practice. Could you comment, @susilehtola, on whether a cmake build is safe for broad use? (Susi packages for Fedora.)

If that's confirmed clear, I agree about switching before 4.3.4. Thanks for your willingness on this. And good luck on `gpaw` and `abinit`. Fortunately, those are outside my sphere of monitoring. :-)

**Comment by susilehtola** [comment]
@loriab I don't know; Fedora is still using autotools. Though if it were up to me, I would have switched libxc over to exclusively CMake years ago...
