### ISSUE TITLE
Enable KXC and LXC

### ISSUE THREAD

**Issue by BastianZim** [conda-forge/libxc-feedstock#26]
Hi,

I'm currently in the process of adding pyscf to conda-forge which depends on libxc. Here, some of my tests fail due to a missing KXC.

Upstream has informed me that this can be solved by compiling with the option `-DDISABLE_KXC=OFF`, as outlined in this issue: https://github.com/pyscf/pyscf/issues/1103

Are you happy with me opening a PR adding that flag?

Additionally, @susilehtola (Who has commented here before) has suggested that `-DDISABLE_LXC=OFF` gets also added to build the full library. This can take a couple of hours so we will have to check if this can be done by conda-forge.

**Comment by jan-janssen** [comment]
Sure - feel free to open the pull request
