### ISSUE TITLE
Can we make libxc available for Apple Silicon via conda-forge?

### ISSUE THREAD

**Issue by yuzie007** [conda-forge/libxc-feedstock#37]
### Comment:

Could you make libxc available also for Apple Silicon MacOS? With this I think it will be easier to install GPAW via pip or conda for Apple Silicon MacOS (currently it seems not easy). I naively guess that we just need to follow https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/ particularly
```yml
build_platform:
  osx_arm64: osx_64
```
but I am not sure what else one should do. If someone knows what to do by heart, I would like to kindly ask. Otherwise I can give a try in future, but not sure when...

**Comment by loriab** [comment]
giving it a try with https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4035

**Comment by yuzie007** [comment]
Thank you @loriab for this addressing the issue. I haven't succeeded to install libxc via conda yet. I guess this may be because I cannot so far use the latest version of conda (23.1.0). I hope this will be soon easily available after next update of anaconda. Then I would like to test this again.

**Comment by loriab** [comment]
I think #42 is ready-to-go, but one won't be able to actually install packages from conda until a few minutes after that PR is merged.
